### ISSUE TITLE
Is RTOS working?

### ISSUE THREAD

**Issue by niclash** [spyren/Mecrisp-Cube#4]
The last commit to rtos.s is marked "WIP" and lack of docs or examples makes it difficult to understand how to use it.

The osThreadNew says "// The new thread needs its own data stack!", but doesn't it need both stacks?

Is it that osThreadNew is more of an internal word, and as a user I should simply "start-task" and two stacks are set up and I am good to go?

In rtos_osNewDataStack there is "ldr r0, =256" and further down a "adds r7, r0, #128". Shouldn't those be the same values (assuming r7 contains top of data stack address)?

Doesn't "terminate" word need to reclaim the allocated data stack?

How is one supposed to create a TCB? Don't we need xTaskCreate() and/or xTaskCreateStatic() wrappers? Or maybe I am just supposed to do `' io-scan TCB construct start-task` (where io-scan is my never-ending background thread/task)

**Comment by spyren** [comment]
`osThreadNew` is low layer without Forth task management. I propose to use task management words. For details see
https://github.com/spyren/Mecrisp-Cube/blob/Flipper/sdcard/man/CmsisRtos.md

I will update the documentation in the master branch, The Flipper branch is the most up-to-date.
